// Generated by CoffeeScript 1.9.2
(function() {
  var resignal;

  resignal = function(times, timespan) {
    var callbacks, log;
    timespan = timespan * 1000;
    log = [];
    callbacks = {
      occured: [],
      report: []
    };
    return {
      on: function(event, callback) {
        if (!(event in callbacks)) {
          throw Error("unknow event type " + event);
        }
        return callbacks[event].push(callback);
      },
      log: function() {
        var cb, i, j, len, len1, now, ref, ref1, start;
        ref = callbacks.occured;
        for (i = 0, len = ref.length; i < len; i++) {
          cb = ref[i];
          cb();
        }
        now = +(new Date);
        start = now - timespan;
        log = log.filter(function(x) {
          return x >= start;
        });
        log.push(+(new Date));
        if (log.length >= times) {
          ref1 = callbacks.report;
          for (j = 0, len1 = ref1.length; j < len1; j++) {
            cb = ref1[j];
            cb();
          }
          return log = [];
        }
      }
    };
  };

  module.exports = resignal;

}).call(this);
